void clearPage();
void welcomeFootball(void);
int randomNo(int f, int l);
void flushBuffer(void);
void printAllPlayers(player_t *players, int size, team_t *teams);
void printTeamPlayers(player_t *players, int size, team_t *teams, int id);
void printAllTeamsList(team_t *teams, int size);
void bubblePlayers(player_t *players, int size, int type);
void bubbleTeams(team_t *teams, int size, int type);
void printLeagueData(team_t *teams, int size);